<?php

/**
 * @file
 * Create (manually or scheduled) and restore backups of your Drupal MySQL
 * database with an option to exclude table data (e.g. cache_*)
 */

use Drupal\Component\Utility\Timer;
use Drupal\backup_migrate\BackupFile;

define('BACKUP_MIGRATE_VERSION', '8.x-2.x');
define('BACKUP_MIGRATE_MENU_PATH', 'admin/config/system/backup_migrate');
define('BACKUP_MIGRATE_MENU_DEPTH', 4);

/* Drupal Hooks */

/**
 * Implementation of hook_help().
 */
function backup_migrate_help($section, $arg) {
  $help = array(
    array(
      'body' =>
       t('Backup and Migrate makes the task of backing up your Drupal database and migrating data from one Drupal install to another easier. It provides a function to backup the entire database to file or download, and to restore from a previous backup. You can also schedule the backup operation. Compression of backup files is also supported.  The database backup files created with this module can be imported into this or any other Drupal installation with the !restorelink, or you can use a database tool such as <a href="!phpmyadminurl">phpMyAdmin</a> or the mysql command line command.',
         array(
            '!restorelink' => \Drupal::currentUser()->hasPermission('restore from backup') ? l(t('restore feature'), BACKUP_MIGRATE_MENU_PATH . '/restore') : t('restore feature'),
            '!phpmyadminurl' => 'http://www.phpmyadmin.net'
          )
        )
    ),
    BACKUP_MIGRATE_MENU_PATH => array(
      'title' => t('Quick Backup Tab'),
      'body' => t('Use this form to run simple manual backups of your database. Visit the !helppage for more help using this module',
                  array('!helppage' => l(t('help page'), 'admin/help/backup_migrate'))),
      'access arguments' => array('perform backup'),
    ),
    BACKUP_MIGRATE_MENU_PATH . '/export/advanced' => array(
      'title' => t('Advanced Backup Tab'),
      'body' => t('Use this form to run manual backups of your database with more advanced options. If you have any !profilelink saved you can load those settings. You can save any of the changes you make to these settings as a new settings profile.',
                  array("!profilelink" => \Drupal::currentUser()->hasPermission('administer backup and migrate') ? l(t('settings profiles'), BACKUP_MIGRATE_MENU_PATH . '/profile') : t('settings profiles'), '!restorelink' => \Drupal::currentUser()->hasPermission('restore from backup') ? l(t('restore feature'), BACKUP_MIGRATE_MENU_PATH . '/restore') : t('restore feature'), '!phpmyadminurl' => 'http://www.phpmyadmin.net')),
      'access arguments' => array('perform backup'),
    ),
    BACKUP_MIGRATE_MENU_PATH . '/restore' => array(
      'title' => t('Restore Tab'),
      'body' => t('Upload a backup and migrate backup file. The restore function will not work with database dumps from other sources such as phpMyAdmin.'),
      'access arguments' => array('restore from backup'),
    ),
    BACKUP_MIGRATE_MENU_PATH . '/destination' => array(
      'title' => t('Destinations'),
      'body' => t('Destinations are the places you can save your backup files to or them load from.'),
      'more' => t('Files can be saved to a directory on your web server, downloaded to your desktop or emailed to a specified email account. From the Destinations tab you can create, delete and edit destinations or list the files which have already been backed up to the available destinations.'),
      'access arguments' => array('administer backup and migrate'),
    ),
    BACKUP_MIGRATE_MENU_PATH . '/profile' => array(
      'title' => t('Profiles'),
      'body' => t('Profiles are saved backup settings. Profiles store your table exclusion settings as well as your backup file name, compression and timestamp settings. You can use profiles in !schedulelink and for !manuallink.',
                  array('!schedulelink' => \Drupal::currentUser()->hasPermission('administer backup and migrate') ? l(t('schedules'), BACKUP_MIGRATE_MENU_PATH . '/schedule') : t('settings profiles'), '!manuallink' => \Drupal::currentUser()->hasPermission('perform backups') ? l(t('manual backups'), BACKUP_MIGRATE_MENU_PATH) : t('manual backups'))),
      'more' => t('You can create new profiles using the add profiles tab or by checking the "Save these settings" button on the advanced backup page.'),
      'access arguments' => array('administer backup and migrate'),
    ),
    BACKUP_MIGRATE_MENU_PATH . '/schedule' => array(
      'title' => t('Scheduling'),
      'body' => t('Automatically backup up your database on a regular schedule using <a href="!cronurl">cron</a>.',
                  array('!cronurl' => 'http://drupal.org/cron')),
      'more' => t('Each schedule will run a maximum of once per cron run, so they will not run more frequently than your cron is configured to run. If you specify a number of backups to keep for a schedule, old backups will be deleted as new ones created. <strong>If specifiy a number of files to keep other backup files in that schedule\'s destination will get deleted</strong>.'),
      'access arguments' => array('administer backup and migrate'),
    ),
  );

  if (isset($help[$section])) {
    return $help[$section]['body'];
  }

  if ($section == 'admin/help#backup_migrate') {
    $out = "";
    foreach ($help as $key => $section) {
      if (isset($section['access arguments'])) {
        foreach($section['access arguments'] as $access) {
          if (!\Drupal::currentUser()->hasPermission($access)) {
            continue 2;
          }
        }
      }
      if (@$section['title']) {
        if (!is_numeric($key)) {
          $section['title'] = l($section['title'], $key);
        }
        $out .= "<h3>". $section['title'] ."</h3>";
      }
      $out .= "<p>". $section['body'] ."</p>";
      if (!empty($section['more'])) {
        $out .= "<p>". $section['more'] ."</p>";
      }
    }
    return $out;
  }
}

/**
 * Implementation of hook_cron().
 *
 * Takes care of scheduled backups and deletes abandoned temp files.
 */
function backup_migrate_cron() {
  // Set the message mode to logging.
  _backup_migrate_message_callback('_backup_migrate_message_log');

  backup_migrate_include('schedules');
  backup_migrate_schedules_run();

  backup_migrate_include('files');
  _backup_migrate_temp_files_delete();
}

/**
 * Implementation of hook_permission().
 */
function backup_migrate_permission() {
  return array(
    'access backup and migrate' => array(
      'title' => t('Access Backup and Migrate'),
      'description' => t('Access the Backup and Migrate admin section.'),
    ),
    'perform backup' => array(
      'title' => t('Perform a backup'),
      'description' => t('Back up any of the available databases.'),
    ),
    'access backup files' => array(
      'title' => t('Access backup files'),
      'description' => t('Access and download the previously created backup files.'),
    ),
    'delete backup files' => array(
      'title' => t('Delete backup files'),
      'description' => t('Delete the previously created backup files.'),
    ),
    'restore from backup' => array(
      'title' => t('Restore the site'),
      'description' => t('Restore the site\'s database from a backup file.'),
    ),
    'administer backup and migrate' => array(
      'title' => t('Administer Backup and Migrate'),
      'description' => t('Edit Backup and Migrate profiles, schedules and destinations.'),
    ),
  );
}

/**
 * Implementation of hook_simpletest().
 */
function backup_migrate_simpletest() {
  $dir = drupal_get_path('module', 'backup_migrate') .'/tests';
  $tests = file_scan_directory($dir, '\.test$');
  return array_keys($tests);
}

/**
 * Implementation of hook_theme().
 */
function backup_migrate_theme() {
  $themes = array(
    'backup_migrate_ui_manual_quick_backup_form' => array(
      'arguments' => array('form'),
      'render element' => 'form',
    ),
  );
  return $themes;
}

/* Menu Callbacks */

/**
 * A menu callback helper. Handles file includes and interactivity setting.
 */
function backup_migrate_menu_callback($include, $function, $interactive = TRUE) {
  if ($include) {
    backup_migrate_include($include);
  }
  // Set the message handler based on interactivity setting.
  _backup_migrate_message_callback($interactive ? '_backup_migrate_message_browser' : '_backup_migrate_message_log');
  // Get the arguments with the first 3 removed.
  $args = array_slice(func_get_args(), 3);
  return call_user_func_array($function, $args);
}

/**
 * Include views .inc files as necessary.
 */
function backup_migrate_include() {
  static $used = array();
  foreach (func_get_args() as $file) {
    if (!isset($used[$file])) {
      require_once DRUPAL_ROOT . '/' . drupal_get_path('module', 'backup_migrate') . "/includes/$file.inc";
    }

    $used[$file] = TRUE;
  }
}

/**
 * Theme the quick backup form.
 */
function theme_backup_migrate_ui_manual_quick_backup_form($form) {
  $form = $form['form'];

  // Remove the titles so that the pulldowns can be displayed inline.
  unset($form['quickbackup']['source_id']['#title']);
  unset($form['quickbackup']['destination_id']['#title']);
  unset($form['quickbackup']['profile_id']['#title']);

  $replacements = array(
    '!from' => drupal_render($form['quickbackup']['source_id']),
    '!to' => drupal_render($form['quickbackup']['destination_id']),
    '!profile' => drupal_render($form['quickbackup']['profile_id']),
    '!submit' => drupal_render($form['quickbackup']['submit']),
  );
  $form['quickbackup']['markup'] = array(
    '#type'   => 'markup',
    "#prefix" => '<div class="container-inline">',
    "#suffix" => '</div>',
    '#markup'  => t('Backup from !from to !to using !profile !submit', $replacements),
  );
  unset($form['quickbackup']['source_id']);
  unset($form['quickbackup']['destination_id']);
  unset($form['quickbackup']['profile_id']);
  unset($form['quickbackup']['submit']);

  return drupal_render_children($form);
}

/**
 * Perform an actual manual backup and tell the user of the progress.
 */
function backup_migrate_ui_manual_backup_perform($settings) {
  // Perform the actual backup.
  backup_migrate_perform_backup($settings);
}

/**
 * Convert an item to an 'exportable'.
 */
function backup_migrate_ui_export_form($form, &$form_state, $item) {
  if ($item && function_exists('ctools_var_export')) {
    $code = ctools_var_export($item);
    $form = ctools_export_form($form_state, $code);
    return $form;
  }
  return array();
}

/**
 * Perform a backup with the given settings.
 */
function backup_migrate_perform_backup(&$settings) {
  backup_migrate_include('destinations', 'files', 'filters');
  Timer::start('backup_migrate_backup');

  // If not in 'safe mode', increase the maximum execution time:
  if (!ini_get('safe_mode') && strpos(ini_get('disable_functions'), 'set_time_limit') === FALSE && ini_get('max_execution_time') < 1200) {
    set_time_limit(\Drupal::config('backup_migrate.settings')->get('max_time.backup'));
  }

  $timestamp = '';
  if ($settings->append_timestamp && $settings->timestamp_format) {
    $timestamp = format_date(time(), 'custom', $settings->timestamp_format);
  }
  $filename = _backup_migrate_construct_filename($settings->filename, $timestamp);

  $file = new BackupFile(array('filename' => $filename));
  if (!$file) {
    backup_migrate_backup_fail("Could not run backup because a temporary file could not be created.", array(), $settings);
    return FALSE;
  }

  // Register shutdown callback to deal with timeouts.
  register_shutdown_function('backup_migrate_shutdown', $settings);

  $file = backup_migrate_filters_backup($file, $settings);
  if (!$file) {
    if (_backup_migrate_check_timeout()) {
      backup_migrate_backup_fail('Could not complete the backup because the script timed out. Try increasing your PHP <a href="!url">max_execution_time setting</a>.', array('!url' => 'http://www.php.net/manual/en/info.configuration.php#ini.max-execution-time'), $settings);
    }
    else {
      backup_migrate_backup_fail("Could not complete the backup.", array(), $settings);
    }
    return FALSE;
  }

  $file = backup_migrate_destination_save_file($file, $settings);
  if (!$file) {
    backup_migrate_backup_fail("Could not run backup because the file could not be saved to the destination.", array(), $settings);
    return FALSE;
  }

  // Backup succeeded,
  $time = Timer::stop('backup_migrate_backup');
  $message = '%source backed up successfully to %file in destination %dest in !time ms. !action';
  $params = array(
    '%file' => $filename,
    '%dest' => $settings->get_destination_name(),
    '%source' => $settings->get_source_name(),
    '!time' => $time['time'],
    '!action' => !empty($settings->performed_action) ? $settings->performed_action : '',
  );
  if (($destination = $settings->get_destination()) && ($links = $destination->get_file_links($file->file_id()))) {
    $params['!links'] = implode(", ", $links);
  }

  backup_migrate_backup_succeed($message, $params, $settings);
  return $file;
}

/**
 * Restore from a file in the given destination.
 */
function backup_migrate_perform_restore($destination_id, $file, $settings = array()) {
  backup_migrate_include('files', 'filters');
  Timer::start('backup_migrate_restore');
  $config = \Drupal::config('backup_migrate.settings');

  // If not in 'safe mode', increase the maximum execution time:
  if (!ini_get('safe_mode')
    && strpos(ini_get('disable_functions'), 'set_time_limit') === FALSE
    && ini_get('max_execution_time') < $config->get('max_time.backup')) {
    set_time_limit($config->get('max_time.restore'));
  }

  // Make the settings into a default profile.
  if (!is_object($settings)) {
    $settings = backup_migrate_crud_create_item('profile', $settings);
    $settings->source_id = empty($settings->source_id) ? 'db' : $settings->source_id;
  }

  // Register shutdown callback.
  register_shutdown_function('backup_migrate_shutdown', $settings);

  if (!is_object($file)) {
    // Load the file from the destination.
    $file = backup_migrate_destination_get_file($destination_id, $file);
    if (!$file) {
      _backup_migrate_message("Could not restore because the file could not be loaded from the destination.", array(), 'error');
      backup_migrate_cleanup();
      return FALSE;
    }
  }
  $file_id = $file->file_id();

  // Filter the file and perform the restore.
  $file = backup_migrate_filters_restore($file, $settings);
  if (!$file) {
    if (_backup_migrate_check_timeout()) {
      backup_migrate_restore_fail('Could not perform the restore because the script timed out. Try increasing your PHP <a href="!url">max_execution_time setting</a>.', array('!url' => 'http://www.php.net/manual/en/info.configuration.php#ini.max-execution-time'), 'error');
    }
    else {
      backup_migrate_restore_fail("Could not perform the restore.", array(), 'error');
    }
    backup_migrate_cleanup();
    return FALSE;
  }

  $time = Timer::stop('backup_migrate_restore');
  if ($file) {
    $destination = backup_migrate_get_destination($destination_id);
    $message = '%source restored from %dest file %file in !time ms. !action';
    $params = array(
      '%file' => $file->filename(),
      '%source' => $settings->get_source_name(),
      '%dest' => $destination->get_name(),
      '!time' => $time['time'],
      '!action' => !empty($settings->performed_action) ? $settings->performed_action : '',
    );
    if ($destination && $destination->op('list files')) {
      $params['!links'] = t('<a href="!restoreurl">Restore again</a>', array('!restoreurl' => url(BACKUP_MIGRATE_MENU_PATH . '/destination/restorefile/'. $destination_id ."/". $file_id)));
    }
    backup_migrate_restore_succeed($message, $params, $settings);
  }
  // Delete any temp files we've created.
  backup_migrate_cleanup();

  // No errors. Return the file.
  return $file;
}

/**
 * Clean up when a backup operation fails.
 */
function backup_migrate_backup_fail($message, $params, $settings) {
  backup_migrate_include('files', 'filters');

  _backup_migrate_message($message, $params, 'error');
  backup_migrate_cleanup();
  backup_migrate_filters_invoke_all('backup_fail', $settings, $message, $params);
  return FALSE;
}

/**
 * Clean up when a backup operation succeeds.
 */
function backup_migrate_backup_succeed($message, $params, $settings) {
  backup_migrate_include('filters', 'files');
  _backup_migrate_message($message, $params, 'success');
  backup_migrate_cleanup();
  backup_migrate_filters_invoke_all('backup_succeed', $settings, $message, $params);
  return FALSE;
}

/**
 * Clean up when a restore operation fails.
 */
function backup_migrate_restore_fail($message, $params, $settings) {
  backup_migrate_include('files', 'filters');
  _backup_migrate_message($message, $params, 'error');
  backup_migrate_cleanup();
  backup_migrate_filters_invoke_all('restore_fail', $settings, $message, $params);
  return FALSE;
}

/**
 * Clean up when a restore operation suceeds.
 */
function backup_migrate_restore_succeed($message, $params, $settings) {
  backup_migrate_include('filters', 'files');
  _backup_migrate_message($message, $params, 'success');
  backup_migrate_cleanup();
  backup_migrate_filters_invoke_all('restore_succeed', $settings, $message, $params);
  return FALSE;
}

/**
 * Cleanup after a success or failure.
 */
function backup_migrate_cleanup() {
  // Check that the cleanup function exists. If it doesn't then we probably didn't create any files to be cleaned up.
  if (function_exists('_backup_migrate_temp_files_delete')) {
    _backup_migrate_temp_files_delete();
  }
}

/**
 * Shutdown callback. Called when the script terminates even if the script timed out.
 */
function backup_migrate_shutdown($settings) {
  // If we ran out of time, set an error so the user knows what happened
  if (_backup_migrate_check_timeout()) {
    backup_migrate_cleanup();
    backup_migrate_backup_fail('The operation timed out. Try increasing your PHP <a href="!url">max_execution_time setting</a>.', array('!url' => 'http://www.php.net/manual/en/info.configuration.php#ini.max-execution-time'), $settings);
    // The session will have already been written and closed, so we need to write any changes directly.
    _drupal_session_write(session_id(), session_encode());
    // Add a redirect or we'll just get whitescreened.
    drupal_goto(BACKUP_MIGRATE_MENU_PATH);
  }
}

/* Utilities */

/**
 * Backup the database with the default settings.
 */
function _backup_migrate_backup_with_defaults($destination_id = "manual") {
  backup_migrate_include('files', 'profiles');

  $settings = _backup_migrate_profile_saved_default_profile();
  $settings->destination_id = $destination_id;
  $settings->source_id = 'db';
  backup_migrate_perform_backup($settings);
}

/**
 * Helper function to set a drupal message and watchdog message depending on whether the module is being run interactively.
 */
function _backup_migrate_message($message, $replace = array(), $type = 'status') {
  // Only set a message if there is a callback handler to handle the message.
  if (($callback = _backup_migrate_message_callback()) && function_exists($callback)) {
    $callback($message, $replace, $type);
  }

  // Store the message in case it's needed (for the status notification filter for example).
  _backup_migrate_messages($message, $replace, $type);
}

/**
 * Helper function to set a drupal message and watchdog message depending on whether the module is being run interactively.
 */
function _backup_migrate_messages($message = NULL, $replace = array(), $type = 'status') {
  static $messages = array();
  if ($message) {
    $messages[] = array('message' => $message, 'replace' => $replace, 'type' => 'status');
  }
  return $messages;
}

/**
 * Send a message to the browser. The normal type of message handling for interactive use.
 */
function _backup_migrate_message_browser($message, $replace, $type) {
  // Log the message as well for admins.
  _backup_migrate_message_log($message, $replace, $type);

  // If there are links, we can display them in the browser.
  if (!empty($replace['!links'])) {
    $message .= " (!links)";
  }
  // Use drupal_set_message to display to the user.
  drupal_set_message(t($message, $replace), str_replace('success', 'status', $type), FALSE);
}

/**
 * Log message if we are in a non-interactive mode such as a cron run.
 */
function _backup_migrate_message_log($message, $replace, $type) {
  // We only want to log the errors or successful completions.
  if (in_array($type, array('error', 'success'))) {
    watchdog('backup_migrate', $message, $replace, $type == 'error' ? WATCHDOG_ERROR : WATCHDOG_NOTICE);
  }
}

/**
 * Set or retrieve a message handler.
 */
function _backup_migrate_message_callback($callback = NULL) {
  static $current_callback = '_backup_migrate_message_log';
  if ($callback !== NULL) {
    $current_callback = $callback;
  }
  return $current_callback;
}

function _backup_migrate_check_timeout() {
  static $timeout;

  // Max execution of 0 means unlimited.
  if (ini_get('max_execution_time') == 0) {
    return false;
  }
  // Figure out when we should stop execution.
  if (!$timeout) {
    $request_time = !empty($_SERVER['REQUEST_TIME']) ? $_SERVER['REQUEST_TIME'] : time();
    $timeout = $request_time + ini_get('max_execution_time') - \Drupal::config('backup_migrate.settings')->get('max_time.timeout_buffer');
  }
  return (time() > $timeout);
}

/**
 * Convert an associated array to an ini format string.
 */
function _backup_migrate_array_to_ini($data, $prefix = '') {
  $content = "";
  foreach ($data as $key => $val) {
    if ($prefix) {
      $key = $prefix . '[' . $key .']';
    }
    if (is_array($val)) {
      $content .= _backup_migrate_array_to_ini($val, $key);
    }
    else {
      $content .= $key . " = \"". $val ."\"\n";
    }
  }
  return $content;
}

/**
 * Execute a command line command. Returns false if the function failed.
 */
function backup_migrate_exec($command, $args = array()) {
  if (!function_exists('exec') || ini_get('safe_mode')) {
    return FALSE;
  }

  // Escape the arguments
  foreach ($args as $key => $arg) {
    $args[$key] = escapeshellarg($arg);
  }
  $command = strtr($command, $args);
  $output = $result = NULL;

  // Run the command.
  exec($command . ' 2>&1', $output, $result);

  return $result == 0;
}

/**
 * Parse an old fashioned ini-style info file.
 */
function backup_migrate_parse_info_file($filename) {
  $data = file_get_contents($filename);
  return backup_migrate_parse_ini_format($data);
}

/**
 * Parse an old fashioned ini-style info data.
 *
 * This is copied from D7 because B&M relies on that formatting.
 */
function backup_migrate_parse_ini_format($data) {
  $info = array();
  $constants = get_defined_constants();

  if (preg_match_all('
    @^\s*                           # Start at the beginning of a line, ignoring leading whitespace
    ((?:
      [^=;\[\]]|                    # Key names cannot contain equal signs, semi-colons or square brackets,
      \[[^\[\]]*\]                  # unless they are balanced and not nested
    )+?)
    \s*=\s*                         # Key/value pairs are separated by equal signs (ignoring white-space)
    (?:
      ("(?:[^"]|(?<=\\\\)")*")|     # Double-quoted string, which may contain slash-escaped quotes/slashes
      (\'(?:[^\']|(?<=\\\\)\')*\')| # Single-quoted string, which may contain slash-escaped quotes/slashes
      ([^\r\n]*?)                   # Non-quoted string
    )\s*$                           # Stop at the next end of a line, ignoring trailing whitespace
    @msx', $data, $matches, PREG_SET_ORDER)) {
    foreach ($matches as $match) {
      // Fetch the key and value string.
      $i = 0;
      foreach (array('key', 'value1', 'value2', 'value3') as $var) {
        $$var = isset($match[++$i]) ? $match[$i] : '';
      }
      $value = stripslashes(substr($value1, 1, -1)) . stripslashes(substr($value2, 1, -1)) . $value3;

      // Parse array syntax.
      $keys = preg_split('/\]?\[/', rtrim($key, ']'));
      $last = array_pop($keys);
      $parent = &$info;

      // Create nested arrays.
      foreach ($keys as $key) {
        if ($key == '') {
          $key = count($parent);
        }
        if (!isset($parent[$key]) || !is_array($parent[$key])) {
          $parent[$key] = array();
        }
        $parent = &$parent[$key];
      }

      // Handle PHP constants.
      if (isset($constants[$value])) {
        $value = $constants[$value];
      }

      // Insert actual value.
      if ($last == '') {
        $last = count($parent);
      }
      $parent[$last] = $value;
    }
  }

  return $info;
}
